import java.net.URI
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

// Release signing is read from keystore.properties when present. To publish an
// update to the existing Play listing this MUST point at the original upload
// key -- a different key produces an APK Play will reject.
val keystoreProperties = Properties().apply {
    val f = rootProject.file("keystore.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}

// The backend's base URL, e.g. https://example.org/api/v1.0/ -- nothing about
// the deployment is hardcoded. First match wins:
//   -PapiBaseUrl=...   (or apiBaseUrl=... in ~/.gradle/gradle.properties)
//   API_BASE_URL=...   environment variable
//   apiBaseUrl=...     in local.properties (gitignored, per machine)
val apiBaseUrl: String = run {
    val localProperties = Properties().apply {
        val f = rootProject.file("local.properties")
        if (f.exists()) f.inputStream().use { load(it) }
    }
    val url = (project.findProperty("apiBaseUrl") as String?)
        ?: System.getenv("API_BASE_URL")
        ?: localProperties.getProperty("apiBaseUrl")
        ?: error("Set the backend URL: -PapiBaseUrl=..., API_BASE_URL=... or apiBaseUrl=... in local.properties")
    // Retrofit resolves relative paths against the base URL, which only works
    // when it ends in a slash.
    if (url.endsWith("/")) url else "$url/"
}
val apiUri: URI = URI(apiBaseUrl)
require(apiUri.scheme in setOf("http", "https") && !apiUri.host.isNullOrEmpty()) {
    "apiBaseUrl must be an absolute http(s) URL, got '$apiBaseUrl'"
}

android {
    namespace = "kz.nu.duryssoile"
    compileSdk = 35

    defaultConfig {
        applicationId = "kz.nu.duryssoile"
        minSdk = 24
        targetSdk = 35
        versionCode = 2
        versionName = "2.0.0"
        resourceConfigurations += listOf("kk", "en")
        buildConfigField("String", "BASE_URL", "\"$apiBaseUrl\"")
    }

    signingConfigs {
        if (keystoreProperties.containsKey("storeFile")) {
            create("release") {
                storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.findByName("release")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
    buildFeatures { compose = true; buildConfig = true }
    packaging { resources.excludes += "/META-INF/{AL2.0,LGPL2.1}" }
}

// network_security_config.xml is generated per variant because it has to name
// the API host, which is only known at build time. Cleartext is permitted for
// that host alone, and only when the URL is http://; debug builds additionally
// allow the emulator's host loopback so they can talk to a local backend.
abstract class NetworkSecurityConfigTask : DefaultTask() {
    @get:Input abstract val cleartextHosts: ListProperty<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val domains = cleartextHosts.get().distinct().joinToString("\n") {
            "        <domain includeSubdomains=\"true\">$it</domain>"
        }
        val domainConfig = if (domains.isEmpty()) "" else """
            |    <domain-config cleartextTrafficPermitted="true">
            |$domains
            |    </domain-config>
            |""".trimMargin()
        val xml = outputDir.get().file("xml/network_security_config.xml").asFile
        xml.parentFile.mkdirs()
        xml.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by NetworkSecurityConfigTask in app/build.gradle.kts. -->
            |<network-security-config>
            |    <base-config cleartextTrafficPermitted="false">
            |        <trust-anchors>
            |            <certificates src="system" />
            |        </trust-anchors>
            |    </base-config>
            |$domainConfig</network-security-config>
            |""".trimMargin()
        )
    }
}

androidComponents {
    onVariants { variant ->
        val task = tasks.register<NetworkSecurityConfigTask>(
            "generate${variant.name.replaceFirstChar { it.uppercase() }}NetworkSecurityConfig"
        ) {
            val apiHost = if (apiUri.scheme == "http") listOf(apiUri.host) else emptyList()
            val loopback = if (variant.buildType == "debug") listOf("10.0.2.2", "localhost") else emptyList()
            cleartextHosts.set(apiHost + loopback)
        }
        variant.sources.res?.addGeneratedSourceDirectory(task, NetworkSecurityConfigTask::outputDir)
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.12.01")
    implementation(composeBom)

    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")

    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")

    implementation("androidx.paging:paging-runtime-ktx:3.3.5")
    implementation("androidx.paging:paging-compose:3.3.5")

    implementation("com.squareup.retrofit2:retrofit:2.11.0")
    implementation("com.squareup.retrofit2:converter-gson:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    debugImplementation("androidx.compose.ui:ui-tooling")

    testImplementation("junit:junit:4.13.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
    testImplementation("androidx.paging:paging-common:3.3.5")
}
